### PR TITLE
Create vehicle.dart

### PR DESCRIPTION
**Pull request by Trisanu-007**
Added classes in dart language.

### CODE REVIEW

**Review by sudhanshutiwari264 — APPROVED** [review]
Perfectly written !

**Comment by Trisanu-007** [comment]
Thanks! It will be better if you include other concepts like inheritance etc.

**Comment by sudhanshutiwari264** [comment]
> Thanks! It will be better if you include other concepts like inheritance etc.

Sure for that I will need help !

**Comment by Trisanu-007** [comment]
Just raise more issues and people will contribute more Ig

**Pull request merged**
