### PR TITLE
Added JavaScript

### PR DESCRIPTION
**Pull request by NinjaLabs-Dev**
Never really dabbled with classes. Didn't realize what I was missing out on

### CODE REVIEW

**Comment by sudhanshutiwari264** [comment]
> Never really dabbled with classes. Didn't realize what I was missing out on

Can you add comment also as it for beginners

**Comment by NinjaLabs-Dev** [comment]
Sure :D

**Review by sudhanshutiwari264 — CHANGES_REQUESTED** [review]
SyntaxError at line NaN: Illegal return statement

**Comment by sudhanshutiwari264** [comment]
ILLEGAL RETURN STATEMENT

**Review by sudhanshutiwari264 — APPROVED** [review]

**Comment by sudhanshutiwari264** [comment]
👍

**Pull request merged**
